- hosts: all
  become: True
  tasks:
    - name: Install apache
      yum:
        name: httpd
        state: present
    - name: Start Apache
      service:
        name: httpd
        state: started
    - name: Enable Apache on Reboot
      service:
        name: httpd
        enabled: True
    - name: Put index.html on apache
      shell: echo  Welcome to Ansible > /var/www/html/index.html
